### PR TITLE
fix whitespace rendering and improve comments

### LINKED ISSUE #602: [content] Markdown inline spans nested within blocks render with extra spaces
When at the top level, this Markdown renders as expected:

```markdown
`abstract` with `sealed`. A [sealed](#sealed) class is
implicitly [abstract](#abstract).

`interface`, `final` or `sealed` with `mixin`. These access modifiers
prevent [mixing in][mixin].
```

However, when rendered within a list element, like:

```markdown
* `abstract` with `sealed`. A [sealed](#sealed) class is
  implicitly [abstract](#abstract).
* `interface`, `final` or `sealed` with `mixin`. These access modifiers
  prevent [mixing in][mixin].
```

There is an extra space added after each inline span and before the periods:

Screenshot of the rendered output

### PR DESCRIPTION
**Pull request by schultek**
## Description

Fixes #602 

## Type of Change

- 🛠️ Bug fix

### CODE REVIEW

File: packages/jaspr/lib/src/server/markup_render_object.dart [hunk 1]
```diff
@@ -57,13 +64,14 @@ abstract class MarkupRenderObject extends RenderObject {
...
     final output = StringBuffer();
+    // Don't increase the indent for fragments.
     final childIndent = this is MarkupRenderFragment ? indent : '$indent  ';
 
     var leadingWhitespace = false;
     var trailingWhitespace = false;
 
     if (children.isNotEmpty) {
-      final childOutput = <(String, bool, bool)>[];
+      final childOutput = <(String, bool, bool, bool)>[];
```
Comment (parlough) [inline packages/jaspr/lib/src/server/markup_render_object.dart]: Consider changing these records to use named fields, as the code later on with the indexed accesses is a bit hard to understand without referring back.

Comment (schultek) [reply packages/jaspr/lib/src/server/markup_render_object.dart]: Agreed
